routes/web.php
<?php

use App\Http\Controllers\Backend\Auth\User\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Auth\ResetPasswordController;
use App\Http\Controllers\Frontend\Auth\UpdatePasswordController;
use App\Http\Controllers\Frontend\User\AccountController;
use App\Http\Controllers\Frontend\User\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Models\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');

/*
 * Frontend Routes
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    Route::get('/post/{post}', function ($post) {
        return view('frontend.post.show', ['post' => Post::findOrFail($post)]);
    })->name('post.show');

    Route::get('/user/{user}/post', [UserController::class, 'getPosts'])->name('user.post.show');

    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        // These routes require no user to be logged in
        Route::group(['middleware' => 'guest'], function () {
            // Authentication Routes
            Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
            Route::post('login', [LoginController::class, 'login'])->name('login.post');
//            Route::post('login', [LoginController::class, 'login'])->name('login.post');
            // Registration Routes
            Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
            Route::post('register', [RegisterController::class, 'register'])->name('register.post');

            Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset.form');
            Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.reset');
        });

        Route::group(['middleware' => 'auth'], function () {
            Route::get('logout', [LoginController::class, 'logout'])->name('logout');

            // Change Password Routes
            Route::patch('password/update', [UpdatePasswordController::class, 'update'])->name('password.update');
        });
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('user/{user_id}/hide_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'hideTweet'])->name('tweet.hide');
        Route::get('user/{user_id}/show_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'showTweet'])->name('tweet.show');
        Route::group(['namespace' => 'User', 'as' => 'user.'], function () {
            // User Account Specific
            Route::get('account', [AccountController::class, 'index'])->name('account');

            // User Profile Specific
            Route::patch('profile/update', [ProfileController::class, 'update'])->name('profile.update');
        });
    });
});

/*
 * Admin Routes
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::group(['middleware' => 'auth'], function () {

        // Post Management
        Route::group(['namespace' => 'Post'], function () {
            // Post CRUD
            Route::get('post', [PostController::class, 'index'])->name('post.index');
            Route::get('post/create', [PostController::class, 'create'])->name('post.create');
            Route::post('post', [PostController::class, 'store'])->name('post.store');

            // Specific Post
            Route::group(['prefix' => 'post/{post}'], function () {
                // Post
                Route::get('/', [PostController::class, 'show'])->name('post.show');
                Route::get('edit', [PostController::class, 'edit'])->name('post.edit');
                Route::patch('/', [PostController::class, 'update'])->name('post.update');
                Route::delete('/', [PostController::class, 'destroy'])->name('post.destroy');
            });
        });

        // All route names are prefixed with 'admin.'.
        Route::redirect('/', '/admin/dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
//    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'author_id',
    ];

    public function author()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Auth::user()->posts()->orderBy('created_at', 'desc')->paginate(5);

        return view('admin.post.index', compact('posts'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->messages()->get('*');
            return response()->json($errors, 400);
        }

        $post = new Post();
        $post->fill($request->all());
        $post->author_id = Auth::user()->id;
        try {
            $post->save();
        } catch (\Exception $e) {
            return response($e->getMessage(), 400);
        }

        return response($post, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('admin.post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->messages()->get('*');
            return response()->json($errors, 400);
        }

        try {
            $post->update($request->all());
        } catch (\Exception $e) {
            return response($e->getMessage(), 400);
        }

        return response($post, 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('admin.post.index')
            ->with('success', 'Post deleted successfully');
    }

    /**
     * @param ManagePostRequest $request
     * @param Post $deletedPost
     *
     * @return mixed
     * @throws \Throwable
     * @throws \App\Exceptions\GeneralException
     */
    public function delete(ManagePostRequest $request, Post $deletedPost)
    {
        $deletedPost->forceDelete();

        return redirect()->route('admin.post.index')->withFlashSuccess(__('alerts.backend.posts.deleted_permanently'));
    }

    /**
     * @param ManagePostRequest $request
     * @param Post $deletedPost
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManagePostRequest $request, Post $deletedPost)
    {
        $this->postRepository->restore($deletedPost);

        return redirect()->route('admin.post.index')->withFlashSuccess(__('alerts.backend.posts.restored'));
    }
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.app')

@section('title', __('labels.backend.access.users.management') . ' | ' . __('labels.backend.access.users.create'))

@section('breadcrumb-links')
    @include('admin.post.includes.breadcrumb-links')
@endsection

@section('content')
    {{ html()->form('POST', route('admin.post.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('labels.backend.access.posts.management')
                        <small class="text-muted">@lang('labels.backend.access.posts.create')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                        {{ html()->label(__('strings.backend.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->attribute('maxlength', 191)
                                ->placeholder(__('strings.backend.title'))
                                ->required()
                                ->autofocus() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('strings.backend.content'))->class('col-md-2 form-control-label')->for('content') }}

                        <div class="col-md-10">
                            {{ html()->textarea('content')
                                ->attribute('rows', 20)
                                ->class('form-control')
                                ->placeholder(__('strings.backend.content'))
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer clearfix">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.post.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    <a id="button-send" class="btn btn-success btn-sm pull-righ" href="#" role="button">
                        {{__('buttons.general.crud.create')}}
                    </a>
                </div><!--col-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
    {{ html()->form()->close() }}
@endsection

@push('after-scripts')
    <script>
        $("form").trigger("reset");
        var arr = (window.location.href).split("/");
        var host = arr[0] + "//" + arr[2]

        $("#button-send").click(function (e) {
            e.preventDefault();
            var settings = {
                "url": $("form").attr('action'),
                "method": "POST",
                "data": $('form').serialize(),
                success: function (data, textStatus, xhr) {
                    showAlert('success', 'The post has been saved', '', 1500);
                    $("form").trigger("reset");
                    window.location = host + "/admin/post";
                },
                error: function (data, textStatus, xhr) {
                    showAlert('error', 'The post could not be been saved', getErrorMessage(data));
                }
            };

            $.ajax(settings);
        });
    </script>
@endpush

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')

@section('title', __('labels.backend.access.posts.management') . ' | ' . __('labels.backend.access.posts.edit'))

@section('breadcrumb-links')
    @include('admin.post.includes.breadcrumb-links')
@endsection

@section('content')
    {{ html()->modelForm($post, 'PATCH', route('admin.post.update', $post->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('labels.backend.access.posts.management')
                        <small class="text-muted">@lang('labels.backend.access.posts.edit')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                        {{ html()->label(__('strings.backend.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->placeholder(__('strings.backend.title'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->

                    <div class="form-group row">
                        {{ html()->label(__('strings.backend.content'))->class('col-md-2 form-control-label')->for('content') }}

                        <div class="col-md-10">
                            {{ html()->textarea('content')
                                ->class('form-control')
                                ->placeholder(__('strings.backend.content'))
                                ->attribute('rows', 20)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.post.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    <a id="button-send" class="btn btn-success btn-sm pull-righ" href="#" role="button">
                        {{__('buttons.general.crud.update')}}
                    </a>
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
    {{ html()->closeModelForm() }}
@endsection
@push('after-scripts')
    <script>
        $("form").trigger("reset");
        var arr = (window.location.href).split("/");
        var host = arr[0] + "//" + arr[2]

        $("#button-send").click(function (e) {
            e.preventDefault();
            var settings = {
                "url": $("form").attr('action'),
                "method": "PATCH",
                "data": $('form').serialize(),
                success: function (data, textStatus, xhr) {
                    showAlert('success', 'The post has been saved', '', 1500);
                    $("form").trigger("reset");
                    window.location = host + "/admin/post";
                },
                error: function (data, textStatus, xhr) {
                    showAlert('error', 'The post could not be been saved', getErrorMessage(data));
                }
            };

            $.ajax(settings);
        });
    </script>
@endpush

resources/views/admin/post/index.blade.php
@extends('admin.layouts.app')

@section('title', app_name() . ' | ' . __('labels.backend.access.posts.management'))

@section('breadcrumb-links')
    @include('admin.post.includes.breadcrumb-links')
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('labels.backend.access.posts.management') }} <small
                            class="text-muted">{{ __('labels.backend.access.posts.all') }}</small>
                    </h4>
                </div><!--col-->

                <div class="col-sm-7">
                    @include('admin.post.includes.header-buttons')
                </div><!--col-->
            </div><!--row-->

            <div class="row mt-4">
                <div class="col">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>@lang('labels.backend.access.posts.table.title')</th>
                                <th>@lang('labels.backend.access.posts.table.content')</th>
                                <th>@lang('labels.backend.access.posts.table.created')</th>
                                <th>@lang('labels.general.actions')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ \Illuminate\Support\Str::words($post->content, 5, ' ...') }}</td>
                                    <td>{{ $post->created_at  }}</td>
                                    <td class="btn-td">@include('admin.post.includes.actions', ['post' => $post])</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div><!--col-->
            </div><!--row-->
            <div class="row">
                <div class="col-7">
                    <div class="float-left">
                        {!! $posts->total() !!} {{ trans_choice('labels.backend.access.posts.table.total', $posts->total()) }}
                    </div>
                </div><!--col-->

                <div class="col-5">
                    <div class="float-right">
                        {!! $posts->render() !!}
                    </div>
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->
    </div><!--card-->
@endsection

resources/views/admin/post/show.blade.php
@extends('admin.layouts.app')

@section('title', __('labels.backend.access.posts.management') . ' | ' . __('labels.backend.access.posts.view'))

@section('breadcrumb-links')
    @include('admin.post.includes.breadcrumb-links')
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('labels.backend.access.posts.management')
                        <small class="text-muted">@lang('labels.backend.access.posts.view')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <div class="row mt-4 mb-4">
                <div class="col">
                    @include('admin.post.show.tabs.overview')
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    <small class="float-right text-muted">
                        <strong>@lang('labels.backend.access.posts.tabs.content.overview.created_at')
                            :</strong> {{ timezone()->convertToLocal($post->created_at) }}
                        ({{ $post->created_at->diffForHumans() }}),
                        <strong>@lang('labels.backend.access.posts.tabs.content.overview.last_updated')
                            :</strong> {{ timezone()->convertToLocal($post->updated_at) }}
                        ({{ $post->updated_at->diffForHumans() }})
                    </small>
                </div><!--col-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
@endsection