routes/web.php
<?php

use App\Http\Controllers\Backend\Auth\User\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Auth\ResetPasswordController;
use App\Http\Controllers\Frontend\Auth\UpdatePasswordController;
use App\Http\Controllers\Frontend\User\AccountController;
use App\Http\Controllers\Frontend\User\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Models\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');

/*
 * Frontend Routes
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    Route::get('/post/{post}', function ($post) {
        return view('frontend.post.show', ['post' => Post::findOrFail($post)]);
    })->name('post.show');

    Route::get('/user/{user}/post', [UserController::class, 'getPosts'])->name('user.post.show');

    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        // These routes require no user to be logged in
        Route::group(['middleware' => 'guest'], function () {
            // Authentication Routes
            Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
            Route::post('login', [LoginController::class, 'login'])->name('login.post');
//            Route::post('login', [LoginController::class, 'login'])->name('login.post');
            // Registration Routes
            Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
            Route::post('register', [RegisterController::class, 'register'])->name('register.post');

            Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset.form');
            Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.reset');
        });

        Route::group(['middleware' => 'auth'], function () {
            Route::get('logout', [LoginController::class, 'logout'])->name('logout');

            // Change Password Routes
            Route::patch('password/update', [UpdatePasswordController::class, 'update'])->name('password.update');
        });
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('user/{user_id}/hide_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'hideTweet'])->name('tweet.hide');
        Route::get('user/{user_id}/show_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'showTweet'])->name('tweet.show');
        Route::group(['namespace' => 'User', 'as' => 'user.'], function () {
            // User Account Specific
            Route::get('account', [AccountController::class, 'index'])->name('account');

            // User Profile Specific
            Route::patch('profile/update', [ProfileController::class, 'update'])->name('profile.update');
        });
    });
});

/*
 * Admin Routes
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::group(['middleware' => 'auth'], function () {

        // Post Management
        Route::group(['namespace' => 'Post'], function () {
            // Post CRUD
            Route::get('post', [PostController::class, 'index'])->name('post.index');
            Route::get('post/create', [PostController::class, 'create'])->name('post.create');
            Route::post('post', [PostController::class, 'store'])->name('post.store');

            // Specific Post
            Route::group(['prefix' => 'post/{post}'], function () {
                // Post
                Route::get('/', [PostController::class, 'show'])->name('post.show');
                Route::get('edit', [PostController::class, 'edit'])->name('post.edit');
                Route::patch('/', [PostController::class, 'update'])->name('post.update');
                Route::delete('/', [PostController::class, 'destroy'])->name('post.destroy');
            });
        });

        // All route names are prefixed with 'admin.'.
        Route::redirect('/', '/admin/dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    });
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
//    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'author_id',
    ];

    public function author()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Auth::user()->posts()->orderBy('created_at', 'desc')->paginate(5);

        return view('admin.post.index', compact('posts'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->messages()->get('*');
            return response()->json($errors, 400);
        }

        $post = new Post();
        $post->fill($request->all());
        $post->author_id = Auth::user()->id;
        try {
            $post->save();
        } catch (\Exception $e) {
            return response($e->getMessage(), 400);
        }

        return response($post, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('admin.post.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->messages()->get('*');
            return response()->json($errors, 400);
        }

        try {
            $post->update($request->all());
        } catch (\Exception $e) {
            return response($e->getMessage(), 400);
        }

        return response($post, 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('admin.post.index')
            ->with('success', 'Post deleted successfully');
    }

    /**
     * @param ManagePostRequest $request
     * @param Post $deletedPost
     *
     * @return mixed
     * @throws \Throwable
     * @throws \App\Exceptions\GeneralException
     */
    public function delete(ManagePostRequest $request, Post $deletedPost)
    {
        $deletedPost->forceDelete();

        return redirect()->route('admin.post.index')->withFlashSuccess(__('alerts.backend.posts.deleted_permanently'));
    }

    /**
     * @param ManagePostRequest $request
     * @param Post $deletedPost
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManagePostRequest $request, Post $deletedPost)
    {
        $this->postRepository->restore($deletedPost);

        return redirect()->route('admin.post.index')->withFlashSuccess(__('alerts.backend.posts.restored'));
    }
}

resources/views/admin/post/includes/actions.blade.php
<div class="btn-group" role="group" aria-label="@lang('labels.backend.access.posts.post_actions')">
    <a href="{{ route('admin.post.show', $post) }}" data-toggle="tooltip" data-placement="top"
       title="@lang('buttons.general.crud.view')" class="btn btn-info">
        <i class="fas fa-eye"></i>
    </a>

    <a href="{{ route('admin.post.edit', $post) }}" data-toggle="tooltip" data-placement="top"
       title="@lang('buttons.general.crud.edit')" class="btn btn-primary">
        <i class="fas fa-edit"></i>
    </a>

    <a href="{{ route('admin.post.destroy', $post) }}"
       data-toggle="tooltip"
       data-placement="top"
       data-method="delete"
       title="@lang('buttons.general.crud.delete')"
       data-trans-button-cancel="@lang('buttons.general.cancel')"
       data-trans-button-confirm="@lang('buttons.general.crud.delete')"
       data-trans-title="@lang('strings.backend.general.are_you_sure')"
       class="btn btn-danger"><i class="fas fa-trash"></i></a>
</div>

resources/views/admin/post/includes/breadcrumb-links.blade.php
{{--<li class="breadcrumb-menu">--}}
{{--    <div class="btn-group" role="group" aria-label="Button group">--}}
{{--        <div class="dropdown">--}}
{{--            <a class="btn dropdown-toggle" href="#" role="button" id="breadcrumb-dropdown-1" data-toggle="dropdown"--}}
{{--               aria-haspopup="true" aria-expanded="false">@lang('menus.backend.access.users.main')</a>--}}
{{--            <div class="dropdown-menu" aria-labelledby="breadcrumb-dropdown-1">--}}
{{--                <a class="dropdown-item"--}}
{{--                   href="{{ route('admin.post.index') }}">@lang('menus.backend.access.users.all')</a>--}}
{{--                <a class="dropdown-item"--}}
{{--                   href="{{ route('admin.post.create') }}">@lang('menus.backend.access.users.create')</a>--}}
{{--            </div>--}}
{{--        </div><!--dropdown-->--}}

{{--        <!--<a class="btn" href="#">Static Link</a>-->--}}
{{--    </div><!--btn-group-->--}}
{{--</li>--}}

resources/views/admin/post/includes/header-buttons.blade.php
<div class="btn-toolbar float-right" role="toolbar" aria-label="@lang('labels.general.toolbar_btn_groups')">
    <a href="{{ route('admin.post.create') }}" class="btn btn-success ml-1" data-toggle="tooltip"
       title="@lang('labels.general.create_new')"><i class="fas fa-plus-circle"></i></a>
</div><!--btn-toolbar-->