routes/web.php
<?php

use App\Http\Controllers\Backend\Auth\User\UserController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Frontend\Auth\LoginController;
use App\Http\Controllers\Frontend\Auth\RegisterController;
use App\Http\Controllers\Frontend\Auth\ResetPasswordController;
use App\Http\Controllers\Frontend\Auth\UpdatePasswordController;
use App\Http\Controllers\Frontend\User\AccountController;
use App\Http\Controllers\Frontend\User\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Models\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');

/*
 * Frontend Routes
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    Route::get('/post/{post}', function ($post) {
        return view('frontend.post.show', ['post' => Post::findOrFail($post)]);
    })->name('post.show');

    Route::get('/user/{user}/post', [UserController::class, 'getPosts'])->name('user.post.show');

    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        // These routes require no user to be logged in
        Route::group(['middleware' => 'guest'], function () {
            // Authentication Routes
            Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
            Route::post('login', [LoginController::class, 'login'])->name('login.post');
//            Route::post('login', [LoginController::class, 'login'])->name('login.post');
            // Registration Routes
            Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
            Route::post('register', [RegisterController::class, 'register'])->name('register.post');

            Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset.form');
            Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.reset');
        });

        Route::group(['middleware' => 'auth'], function () {
            Route::get('logout', [LoginController::class, 'logout'])->name('logout');

            // Change Password Routes
            Route::patch('password/update', [UpdatePasswordController::class, 'update'])->name('password.update');
        });
    });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('user/{user_id}/hide_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'hideTweet'])->name('tweet.hide');
        Route::get('user/{user_id}/show_tweet/{tweet_id}', [\App\Http\Controllers\TweetController::class, 'showTweet'])->name('tweet.show');
        Route::group(['namespace' => 'User', 'as' => 'user.'], function () {
            // User Account Specific
            Route::get('account', [AccountController::class, 'index'])->name('account');

            // User Profile Specific
            Route::patch('profile/update', [ProfileController::class, 'update'])->name('profile.update');
        });
    });
});

/*
 * Admin Routes
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::group(['middleware' => 'auth'], function () {

        // Post Management
        Route::group(['namespace' => 'Post'], function () {
            // Post CRUD
            Route::get('post', [PostController::class, 'index'])->name('post.index');
            Route::get('post/create', [PostController::class, 'create'])->name('post.create');
            Route::post('post', [PostController::class, 'store'])->name('post.store');

            // Specific Post
            Route::group(['prefix' => 'post/{post}'], function () {
                // Post
                Route::get('/', [PostController::class, 'show'])->name('post.show');
                Route::get('edit', [PostController::class, 'edit'])->name('post.edit');
                Route::patch('/', [PostController::class, 'update'])->name('post.update');
                Route::delete('/', [PostController::class, 'destroy'])->name('post.destroy');
            });
        });

        // All route names are prefixed with 'admin.'.
        Route::redirect('/', '/admin/dashboard', 301);
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    });
});

resources/views/admin/includes/footer.blade.php
<footer class="app-footer">
</footer>

resources/views/admin/includes/header.blade.php
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">
        <img class="navbar-brand-full" src="{{ asset('img/backend/brand/logo.svg') }}" width="89" height="25"
             alt="Jobsity">
        <img class="navbar-brand-minimized" src="{{ asset('img/backend/brand/sygnet.svg') }}" width="30" height="30"
             alt="Jobsity">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">
        <li class="nav-item px-3">
            <a class="nav-link" href="{{ route('index') }}"><i class="fas fa-home"></i></a>
        </li>

        <li class="nav-item px-3">
            <a class="nav-link" href="{{ route('admin.dashboard') }}">@lang('navs.frontend.dashboard')</a>
        </li>

        @if(config('locale.status') && count(config('locale.languages')) > 1)
            <li class="nav-item px-3 dropdown">
                <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="d-md-down-none">@lang('menus.language-picker.language') ({{ strtoupper(app()->getLocale()) }})</span>
                </a>
            </li>
        @endif
    </ul>

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">
                <img src="{{asset('avatar.png')}}" class="img-avatar" alt="{{ $logged_in_user->email }}">
                <span class="d-md-down-none">{{ $logged_in_user->username }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('frontend.user.account') }}"
                   class="dropdown-item {{ active_class(Route::is('frontend.user.account')) }}">@lang('navs.frontend.user.account')</a>

                <a class="dropdown-item" href="{{ route('frontend.auth.logout') }}">
                    <i class="fas fa-lock"></i> @lang('navs.general.logout')
                </a>
            </div>
        </li>
    </ul>
</header>

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-title">
                @lang('menus.backend.sidebar.general')
            </li>
            <li class="nav-item">
                <a class="nav-link {{
                    active_class(Route::is('admin/dashboard'))
                }}" href="{{ route('admin.dashboard') }}">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    @lang('menus.backend.sidebar.dashboard')
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{
                    active_class(Route::is('admin/auth/user*'))
                    }}" href="{{ route('admin.post.index') }}">
                    <i class="nav-icon fas fa-newspaper"></i>
                    @lang('labels.backend.access.posts.management')
                </a>
            </li>
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div><!--sidebar-->